image: docker:latest
services:
  - docker:dind

stages:
  - build

build:
  stage: build
  variables:
     CONTAINER_IMAGE: ${IMAGE}:${CI_COMMIT_SHORT_SHA}
  script:
    - sleep 5
    - docker info
    - docker login -u $CI_REGISTRY_USER -P $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CONTAINER_IMAGE
    - docker push $CONTAINER_IMAGE


